[phases.setup]
nixPkgs = ["python310", "gcc", "libGL"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn mangoAPI.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 300 --log-level debug --access-logfile - --error-logfile -"
