# Generated by Django 5.1.7 on 2025-09-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0006_alter_predictionlog_response_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
