# Generated by Django 5.1.7 on 2025-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0007_userprofile_barangay_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='location_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='location_consent_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='location_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
