# Generated by Django 5.1.7 on 2025-09-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0008_mangoimage_latitude_mangoimage_location_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='user_feedback',
            field=models.TextField(blank=True),
        ),
    ]
