# Generated by Django 5.1.7 on 2025-09-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0009_mangoimage_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='user_confirmed_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
