# Generated by Django 5.1.7 on 2025-09-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0010_mangoimage_user_confirmed_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='location_accuracy_confirmed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
