# Generated by Django 5.1.7 on 2025-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0011_mangoimage_location_accuracy_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='alternative_symptoms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='detected_disease',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='primary_symptoms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='selected_symptoms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='symptoms_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangoimage',
            name='top_diseases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
