# Generated by Django 5.1.7 on 2025-10-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0012_mangoimage_alternative_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangoimage',
            name='user_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
