# Generated by Django 5.1.7 on 2025-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0013_fix_user_feedback_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='model_used',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
