# Generated by Django 5.1.7 on 2025-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangosense', '0014_mangoimage_model_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangoimage',
            name='model_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
